# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:APFVxGNRQI/7giPpsoo8tGY=,iv:rcS/pVpVWaNRUiKcVEhGmhAqCO9U2l+PVPQdDFWThZM=,tag:dQpxPQiqeXsTK0pkPph7Gg==,type:str]
    #ENC[AES256_GCM,data:uDqaMCu4vO3+EHBg/Ry9yBBUGZeo49TVd2c=,iv:ZH1dBAytUlwJdmahyb5PQSjfZgdr9lY2GfUPKeb6RIk=,tag:/Kmj0QLc74qLSuL6HbO/ZQ==,type:comment]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-11-03T12:44:35Z"
    mac: ENC[AES256_GCM,data:I1kRIWWRLGUNDMXIHKYjtSa+FJNqXNT6ja0CUjB3TUgwa0mOPz6hQakGCwaZwX6BdP98HZiz6/WJRjxgP6zYUgTmF6N43NwyYMvZw7a4/9jya1dQj+TYbcj8bbKbIHtgkrshDdp7vyRfEx8osDvQTr+VWf+AYsa6mDjT/H0FRrc=,iv:/az+Rr45nEDoEBe2Y7ymQpQMVMNBUQ1/+sJOd+U6kpI=,tag:1j0G4/iHoo8OeLS8Wc3m2A==,type:str]
    pgp:
        - created_at: "2022-11-03T12:44:34Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAxsdYzDqUimJAQ//RBXZwWsblynzbM1f01smKLrtPbgnEXoTHz5ZX5nkIftu
            HR1OThXoi8gOB4svmJL8v42uIxC0WmNEZtWykGChYPGzw011/AVS9uZsK2UXYu1h
            qvRWilX3xuX8VB3vWV3PgwxLimIoO0Dde1Oh0+f96j6q9h7DQYsij7CllOlhDion
            SN8EmirLGaSkahyvUgtjNNS5m/8uPYlBD2ND4yqyE8vPlH2pNbDaaiIWbQ109Nt2
            JD1t4f3X+CDLqsfud5RwodMgBRt9zhLkBpaPr9mTb7D6hKhaMljQaoXqNze+CPFW
            7M7+TPzIyrgASO/7UuY0Ng0vOAm0D6r8vUNwP7M9GhkeUc6ECWPMpXqsCqeJ2Tpv
            ioUyGW4if8ziq0U1k1h8QgGrlSS5NZntfYaA8+XQD0pkWzI+1GSgMZONEuhveqBU
            c28ULIUyata4StxYIVGQiC/mNCZdmluAHRowhzl5oH1oG3ucBcPtgJi3jlikF/J1
            OWPNT43M/GMCOf5ofXWHJse0Oni5eUUqeAzCVU/saEO39qrx4RIH//djD558yGrJ
            Do2F1dWiDW1ecKfCYHnWKGPDGRhAP7Yiprpjg3cUk1YsuD7nIC4JQGTQZOtPRuAK
            DF2aetJTtGS2/HrvgX6I3+MuNVHNeZFNIB5GiGSDOFwl9KHB3PlJhYrvO8fXD1PS
            XgEC0m/bi0cqlc6NZmBkI8E9rKY+qgZaF9RqsopnBRSj9Iy0SF12KIRuveneDrbA
            WDndADQSOJZgOan5BEm4mIY1a5v3JNKjQEf0HLOD9Zf+CJJSCybw2dZzl4/Nt60=
            =rMyA
            -----END PGP MESSAGE-----
          fp: 76007DAE678227B82F926E32DB096AB4FC2604D4
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
