---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: core
  namespace: flux-system
spec:
  interval: 30m
  path: ./cluster/core
  prune: false
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  dependsOn:
    - name: config
    - name: charts
  decryption:
    provider: sops
    secretRef:
      name: sops
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets