---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: demo-apps
  namespace: flux-system
spec:
  interval: 30m
  path: ./cluster/demo-apps
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  dependsOn:
    - name: bigbang
  decryption:
    provider: sops
    secretRef:
      name: sops
  postBuild:
    substituteFrom:
      - kind: ConfigMap
        name: cluster-settings
      - kind: Secret
        name: cluster-secrets
